@ASP.NETCoreAPI_HostAddress = http://localhost:5251


GET {{ASP.NETCoreAPI_HostAddress}}/
Accept: application/json

###
GET {{ASP.NETCoreAPI_HostAddress}}/greeting?name=testes
Accept: application/json

###
GET {{ASP.NETCoreAPI_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{ASP.NETCoreAPI_HostAddress}}/math/sum/5/5
Accept: application/json

###
GET {{ASP.NETCoreAPI_HostAddress}}/math/sum/-5/4
Accept: application/json

###
GET {{ASP.NETCoreAPI_HostAddress}}/math/sub/55/10
Accept: application/json

###
GET {{ASP.NETCoreAPI_HostAddress}}/math/med/40/10
Accept: application/json

###
GET {{ASP.NETCoreAPI_HostAddress}}/math/div/100/0
Accept: application/json

###
GET {{ASP.NETCoreAPI_HostAddress}}/math/square-root/-4
Accept: application/json


### --------------------------------------------------------- ROTAS DE "PERSON"

###
GET {{ASP.NETCoreAPI_HostAddress}}/person
Accept: application/json

###
GET {{ASP.NETCoreAPI_HostAddress}}/person/2
Accept: application/json

###
POST {{ASP.NETCoreAPI_HostAddress}}/person
Content-Type: application/json

{
  "FirstName": "Novo usuário",
  "LastName": "Sobrenome asdasdasdasda",
  "Address": "Rua Fulano de tal 321",
  "Gender": "Male"
}

###
PATCH {{ASP.NETCoreAPI_HostAddress}}/person
Content-Type: application/json
{
  "Id": 2,
  "LastName": "Sobrenome Fulano 2"  
}


###
DELETE {{ASP.NETCoreAPI_HostAddress}}/person/1
Content-Type: application/json

### -------------------- Fim rotas de "PERSON"




### -------------------- ROTAS DE "TO DO"
GET {{ASP.NETCoreAPI_HostAddress}}/todoitem?page=2&size=10
Content-Type: application/json

###
GET {{ASP.NETCoreAPI_HostAddress}}/todoitem/1
Content-Type: application/json


### 
GET {{ASP.NETCoreAPI_HostAddress}}/todoitem?title=Tarefa+1
Content-Type: application/json



###
POST {{ASP.NETCoreAPI_HostAddress}}/todoitem/
Content-Type: application/json

{
  "Title" : "Tarefa999",
  "Description" : "Tarefa999: fazer as tarefas de hoje333...",
  "IsDone" : false
}

###
PATCH {{ASP.NETCoreAPI_HostAddress}}/todoitem/
Content-Type: application/json

{
  "Id" : 2,
  "IsDone" : false
}


###
DELETE {{ASP.NETCoreAPI_HostAddress}}/todoitem/1
Content-Type: application/json



### -------------------- ROTAS DE "BOOKS"
GET {{ASP.NETCoreAPI_HostAddress}}/book?page=1&size=20
Content-Type: application/json

###
GET {{ASP.NETCoreAPI_HostAddress}}/book/16
Content-Type: application/json


###
POST {{ASP.NETCoreAPI_HostAddress}}/book
Content-Type: application/json
{  
  "Title" : "Livro Teste",
  "Author" : "Autor Teste",
  "Price" : 19.99,
  "Launch_date" : "2024-06-01T00:00:00"
}


###
PATCH {{ASP.NETCoreAPI_HostAddress}}/book
Content-Type: application/json
{
  "Id" : 17,
  "Title": "Livro Teste Atualizado"
}

###
DELETE {{ASP.NETCoreAPI_HostAddress}}/book/16
Content-Type: application/json
