// <auto-generated />
using System;
using ASP.NETCoreAPI.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ASP.NETCoreAPI.Migrations
{
    [DbContext(typeof(PostgreSQLContext))]
    partial class PostgreSQLContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ASP.NETCoreAPI.Models.Book", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("author");

                    b.Property<DateTime>("Launch_date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("launch_date");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("book", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Author = "Michael C. Feathers",
                            Launch_date = new DateTime(2004, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 49.00m,
                            Title = "Working Effectively with Legacy Code"
                        },
                        new
                        {
                            Id = 2L,
                            Author = "Ralph Johnson, Erich Gamma, John Vlissides, Richard Helm",
                            Launch_date = new DateTime(1994, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 45.00m,
                            Title = "Design Patterns: Elements of Reusable Object-Oriented Software"
                        },
                        new
                        {
                            Id = 3L,
                            Author = "Robert C. Martin",
                            Launch_date = new DateTime(2008, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 77.00m,
                            Title = "Clean Code: A Handbook of Agile Software Craftsmanship"
                        },
                        new
                        {
                            Id = 4L,
                            Author = "Douglas Crockford",
                            Launch_date = new DateTime(2008, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 67.00m,
                            Title = "JavaScript: The Good Parts"
                        },
                        new
                        {
                            Id = 5L,
                            Author = "Steve McConnell",
                            Launch_date = new DateTime(2004, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 58.00m,
                            Title = "Code Complete (2nd Edition)"
                        },
                        new
                        {
                            Id = 6L,
                            Author = "Martin Fowler, Kent Beck",
                            Launch_date = new DateTime(1999, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 88.00m,
                            Title = "Refactoring: Improving the Design of Existing Code"
                        },
                        new
                        {
                            Id = 7L,
                            Author = "Eric Freeman, Elisabeth Freeman, Kathy Sierra, Bert Bates",
                            Launch_date = new DateTime(2004, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 110.00m,
                            Title = "Head First Design Patterns"
                        },
                        new
                        {
                            Id = 8L,
                            Author = "Eric Evans",
                            Launch_date = new DateTime(2003, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 92.00m,
                            Title = "Domain-Driven Design: Tackling Complexity in the Heart of Software"
                        },
                        new
                        {
                            Id = 9L,
                            Author = "Brian Goetz, Tim Peierls",
                            Launch_date = new DateTime(2006, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 80.00m,
                            Title = "Java Concurrency in Practice"
                        },
                        new
                        {
                            Id = 10L,
                            Author = "Susan Cain",
                            Launch_date = new DateTime(2012, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 123.00m,
                            Title = "Quiet: The Power of Introverts in a World That Can''t Stop Talking"
                        },
                        new
                        {
                            Id = 11L,
                            Author = "Roger S. Pressman",
                            Launch_date = new DateTime(2009, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 56.00m,
                            Title = "Software Engineering: A Practitioner''s Approach (7th Edition)"
                        },
                        new
                        {
                            Id = 12L,
                            Author = "Viktor Mayer-Schonberger, Kenneth Kukier",
                            Launch_date = new DateTime(2013, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 54.00m,
                            Title = "Big Data: A Revolution That Will Transform How We Live, Work, and Think"
                        },
                        new
                        {
                            Id = 13L,
                            Author = "Richard Hunter, George Westerman",
                            Launch_date = new DateTime(2009, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 95.00m,
                            Title = "The Real Business of IT: How CIOs Create and Communicate Value"
                        },
                        new
                        {
                            Id = 14L,
                            Author = "Aguinaldo Aragon Fernandes, Vladimir Ferraz de Abreu",
                            Launch_date = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 54.00m,
                            Title = "Implementing IT Governance: A Practical Guide to Global Best Practices in IT Management"
                        },
                        new
                        {
                            Id = 15L,
                            Author = "Marc J. Schiller",
                            Launch_date = new DateTime(2012, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 45.00m,
                            Title = "The 11 Secrets of Highly Influential IT Leaders"
                        });
                });

            modelBuilder.Entity("ASP.NETCoreAPI.Models.Person", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("address");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("last_name");

                    b.HasKey("Id");

                    b.ToTable("person");
                });

            modelBuilder.Entity("ASP.NETCoreAPI.Models.TodoItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDone")
                        .HasColumnType("boolean")
                        .HasColumnName("is_done");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("todo_items");
                });
#pragma warning restore 612, 618
        }
    }
}
